In [1]:
import tensorflow as tf
import numpy as np
from model import AttentionSeq2Seq

In [2]:
# integrated testing
batch_size = 3
enc_sequence_len = 3
dec_sequence_len = 4
symbol_size = 10
embedding_size = 64
hidden_size = 3
layer_size = 1

x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
Y = np.array([[1,2,3,4],
              [5,6,7,8],
              [7,8,9,0]])

S = np.array([[0],
              [0],
              [0]])

sess = tf.Session()

model = AttentionSeq2Seq(sess,
                         batch_size,
                         enc_sequence_len, 
                         dec_sequence_len,
                         symbol_size,
                         symbol_size,
                         embedding_size,
                         hidden_size)

sess.run(tf.global_variables_initializer())

for _ in range(10):
    loss, _ = model.train(x, Y, Y)
    print(loss)

pred = model.prediction(x, S)
print(pred)

2.22547
2.0272
1.74798
1.58104
1.39543
1.24363
1.15733
1.07998
1.00791
0.948618
[[[0]
  [2]
  [7]
  [0]]

 [[7]
  [2]
  [7]
  [0]]

 [[7]
  [8]
  [7]
  [0]]]


In [2]:
batch_size = 3
enc_sequence_len = 3
dec_sequence_len = 4
symbol_size = 10
embedding_size = 64
hidden_size = 3
layer_size = 1

sess = tf.Session()

model = AttentionSeq2Seq(sess,
                         batch_size,
                         enc_sequence_len, 
                         dec_sequence_len,
                         symbol_size,
                         symbol_size,
                         embedding_size,
                         hidden_size)

model.test_decoder_pred()

decoder/embeddings
decoder/decoder_0_step/rnn/transpose decoder/decoder_0_step/rnn/while/Exit_2
decoder/decoder_0_step/fully_connected/Relu
decoder/decoder_1_step/rnn/transpose decoder/decoder_1_step/rnn/while/Exit_2
decoder/decoder_1_step/fully_connected/Relu
decoder/decoder_2_step/rnn/transpose decoder/decoder_2_step/rnn/while/Exit_2
decoder/decoder_2_step/fully_connected/Relu
decoder/decoder_3_step/rnn/transpose decoder/decoder_3_step/rnn/while/Exit_2
decoder/decoder_3_step/fully_connected/Relu
decoder_train_END
decoder/embeddings
decoder_1/decoder_0_step/rnn/transpose decoder_1/decoder_0_step/rnn/while/Exit_2
decoder_1/decoder_0_step/fully_connected/Relu
decoder_1/decoder_1_step/rnn/transpose decoder_1/decoder_1_step/rnn/while/Exit_2
decoder_1/decoder_1_step/fully_connected/Relu
decoder_1/decoder_2_step/rnn/transpose decoder_1/decoder_2_step/rnn/while/Exit_2
decoder_1/decoder_2_step/fully_connected/Relu
decoder_1/decoder_3_step/rnn/transpose decoder_1/decoder_3_step/rnn/while/Exit_